### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by kersten** [bergwerk/bwrk_address#2]
Would you mind to merge my pull request #1

**Comment by marvinhuebner** [comment]
We have already added a composer.json. See https://github.com/bergwerk/bwrk_address/commit/2749d5a02548cc459687864cd5bafb6a97c3bfeb. Will close this issue. Sorry for ignoring #1. 

But thanks for the hint and using our extension.

**Comment by kersten** [comment]
You forgot some stuff like psr-4 in your composer.json
